server:
  port: 6001
spring:
  application:
    name: SpringClougGatewaySetUp
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - routes[0]:
#                id: learning-route
#                uri: http://localhost:6001
#                predicates[0]:
#                  - Path=/api/learning/**
#                filters[0]:
#                  - StripPrefix=1
#            - routes[1]:
#                id: learning-route
#                uri: http://localhost:6002/
#                predicates[0]:
#                  - Path=/api/learning/**
#                filters[0]:
#                  - StripPrefix=1
